### ISSUE TITLE
Unitialized constant error

### ISSUE THREAD

**Issue by jnb** [airbnb/nerve#20]
I got the following  error when running Nerve under Ruby 1.8:

```
nerve/lib/nerve/service_watcher/tcp.rb:53: uninitialized constant Nerve::ServiceCheck::CHECKS (NameError)
        from nerve/lib/nerve/service_watcher.rb:1:in `require'
        from nerve/lib/nerve/service_watcher.rb:1
        from nerve/lib/nerve.rb:10:in `require'
        from nerve/lib/nerve.rb:10
        from bin/nerve:6:in `require'
        from bin/nerve:6
```

I hacked around it by defining `CHECKS = {}` in `lib/nerve/service_watcher/base.rb`, but there might be a cleaner way?

**Comment by iamthemuffinman** [comment]
Looks like that was fixed here: https://github.com/airbnb/nerve/commit/6e043d93eb63ef665dff99a63a7ca605021bc3d6 so this issue can probably be closed.

**Comment by jolynch** [comment]
indeed, thanks for the heads up.
