### ISSUE TITLE
serf Support

### ISSUE THREAD

**Issue by ahelal** [airbnb/nerve#72]
Hi,

We are using smartstack for over a year and we love it, But we use the [getyourguide](https://github.com/getyourguide) fork that uses serf. And then we forked that and using our or branch. 

I would like to avoid this fork nightmare. Are you open for serf reporter PR ?

**Comment by jolynch** [comment]
Nerve supports custom reporters by automatically requiring modules by name. See https://github.com/airbnb/nerve/blob/master/lib/nerve/reporter.rb for how this works. All you've got to do is make your reporter available for require. We're working on adding the same pluggable interface to Synapse.

Is the fork more substantial than the reporter itself?

**Comment by ahelal** [comment]
Thank you, I will try to move to the plugin model that seems as a better option

**Comment by jolynch** [comment]
@ahelal, let me know if you have any issues with integration. I'm working on the Synapse support right now.

@igor47, do we want to create a howto guide for this?

**Comment by ahelal** [comment]
@jolynch, I am currently on vacation. Will start working on that next week. I will dig in the code and raise issues as I go.
