### ISSUE TITLE
Should nerve consider a 3xx status to be successful?

### ISSUE THREAD

**Issue by EvanKrall** [airbnb/nerve#77]
Context: https://github.com/Yelp/hacheck/pull/4

We discovered one of our services (mistakenly) returning 3xx status codes; [hacheck](https://github.com/Yelp/hacheck/pull/4) was following the redirects.

We want to fix that, but Nerve considers 3xx to be health check failures.

HAProxy, nginx, Marathon all consider 3xx status codes to be healthy. IMO nerve should be consistent with these other healthcheck consumers (Particularly HAProxy, which nerve is designed to work with).

**Comment by jolynch** [comment]
Yea I think it's pretty standard practice to treat 3xxs as healthy. @igor47 @rickypai any objections to #78
