### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by iamthemuffinman** [airbnb/nerve#94]
Does Airbnb still use Synapse and Nerve for service discovery? There doesn't seem to be much activity on either project.

**Comment by jolynch** [comment]
I can't speak to Airbnb but we pretty heavily rely on Nerve and Synapse here at Yelp.

I'm not sure what you mean by lack of activity? Both projects are fully pluggable and mostly feature complete, so customers can plugin their own functionality without merging it back to the main project (e.g. adding [nginx to Synapse](https://github.com/jolynch/synapse-nginx)). Regarding Nerve in particular I think most people use aurora or finagle and just use Synapse's built in ability to detect those serverset definitions.

I did merge some fixes to core Synapse back in April that fixed some minor performance issues with extremely high churn setups (like millions of LB updates per day), but ... not much really needs to be fixed there.

There are certainly some open PRs that might be worth merging, but most of the "add X config generator or service watchers" can be independently published as separate gems now so ...

**Comment by iamthemuffinman** [comment]
By lack of activity, I mean the last commit was November 2016, all open issues are old and stale, and all PR's are old and stale. Those are the metrics by which I judge a project.

Both projects seem to have reached a level of maturity where they don't require constant attention.  I was curious about the state of both projects because I'm considering using them at my current gig.

Thanks for the reply!
